name: Deploy Docs
on:
  push:
    branches:
      - 'main'
      - '*.x'
      - '!gh-pages'
    tags:
      - 'v*'
  repository_dispatch:
    types: request-build-reference # legacy
  workflow_dispatch:
permissions:
  actions: write
jobs:
  build:
    name: Dispatch docs deployment
    if: github.repository_owner == 'spring-projects'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: docs-build
    - name: Dispatch (partial build)
      if: github.ref_type == 'branch'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh workflow run deploy-docs.yml -r $(git rev-parse --abbrev-ref HEAD) -f build-refname=${{ github.ref_name }}
    - name: Dispatch (full build)
      if: github.ref_type == 'tag'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh workflow run deploy-docs.yml -r $(git rev-parse --abbrev-ref HEAD)
